// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MULI_PluginBase","status":true,"description":"v1.0.0","parameters":{}},
{"name":"MULI_IgnoreNotFound","status":true,"description":"v0.1.0","parameters":{}}
];
